version: '3.7'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "todo@123"
        ACCEPT_EULA: "Y"
    restart: always

  api:
    build: "./"
    container_name: rush-todo-container
    restart: always
    ports:
      - "9001:9001"
    depends_on:
      - db